planilha/accounts/urls.py
from django.urls import path

from planilha.accounts import views

app_name = 'accounts'


urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('sair/', views.logout_view, name='logout'),
    path(
        'mudar-senha/', views.CustomPasswordChangeView.as_view(), name='change-password'
    ),
]

planilha/core/urls.py
from django.urls import path

from planilha.core import views

app_name = 'core'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('deletar/<int:pk>/<str:month>', views.delete_spent_view, name='delete'),
    path(
        'alterar/<int:pk>/<str:month>/<int:year>',
        views.update_spent_view,
        name='update',
    ),
    path('adicionar/<str:month>/<int:year>', views.create_spent_view, name='create'),
    path('renda/<str:month>/<int:year>', views.income_view, name='income'),
    path('mes/<str:month>/', views.month_view, name='month'),
]

planilha/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('planilha.core.urls')),
    path('', include('planilha.accounts.urls')),
] + static(settings.MEDIA_URL, document=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

planilha/accounts/models.py
# from django.db import models
# Create your models here.

planilha/accounts/forms.py
from django import forms
from django.contrib.auth.models import User

from planilha.core.models import Income


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(label='Senha atual', widget=forms.PasswordInput())
    new_password1 = forms.CharField(label='Nova senha', widget=forms.PasswordInput())
    new_password2 = forms.CharField(
        label='Repita a nova senha', widget=forms.PasswordInput(),
    )

    class Meta:
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def clean(self):
        old_password = self.cleaned_data.get('old_password')
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')

        if len(password1) < 6 or len(password2) < 6:
            self.add_error('new_password2', 'Senha deve conter 6 ou mais carácteres!')

        if not self.user.check_password(old_password):
            self.add_error('old_password', 'Senha incorreta!')

        if password1 != password2:
            self.add_error('new_password2', 'Senhas não conferem!')

    def save(self):
        new_password = self.cleaned_data.get('new_password2')
        self.user.set_password(new_password)
        self.user.save()

        return self.user


class RegisterForm(forms.Form):
    username = forms.CharField(label='Usuário')
    email = forms.EmailField()
    password = forms.CharField(
        label='Senha',
        help_text='senha precisa ter 6 ou mais carácteres.',
        widget=forms.PasswordInput(),
    )
    password2 = forms.CharField(label='Repetir Senha', widget=forms.PasswordInput())

    class Meta:
        fields = '__all__'

    def clean(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')

        if User.objects.filter(username=username).exists():
            return self.add_error('username', 'usuário já existe.')

        if User.objects.filter(email=email).exists():
            return self.add_error('email', 'email já existe.')

        if len(password) < 6 or len(password2) < 6:
            return self.add_error('password', 'senha precisa ter 6 ou mais carácteres.')

        if password != password2:
            return self.add_error('password2', 'senhas não conferem')

    def save(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        user = User.objects.create_user(
            username=username, email=email, password=password
        )
        user.save()

        Income.objects.create(user=user)

planilha/accounts/views.py
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator

from planilha.accounts import forms


@method_decorator(login_required, name='dispatch')
class CustomPasswordChangeView(auth_views.PasswordChangeView):
    form_class = forms.ChangePasswordForm
    template_name = 'accounts/change-password.html'
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        form.save()

        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Senha Alterada com SUCESSO. Refaça o login!',
        )
        logout(self.request)
        return super().form_valid(form)


def register_view(request):
    form = forms.RegisterForm()
    if request.method == 'POST':
        form = forms.RegisterForm(data=request.POST)

        if form.is_valid():
            form.save()

            messages.success(
                request, 'Cadastro realizado com sucesso. Faça o login abaixo.'
            )
            return redirect('accounts:login')

    return render(request, 'accounts/register.html', {'form': form})


def login_view(request):
    form = AuthenticationForm()

    if request.method == 'POST':
        post = request.POST.copy()
        form = AuthenticationForm(data=post)

        if form.is_valid():
            auth.login(request, form.get_user())

            messages.success(request, 'Login realizado com sucesso.')
            return redirect('core:home')

        messages.error(
            request, 'Usuário não encontrado. Verifique se preencheu corretamente.'
        )

        return redirect('accounts:login')

    return render(request, 'accounts/login.html', {'form': form})


@login_required
def logout_view(request):
    auth.logout(request)

    messages.info(request, 'Você foi deslogado.')
    return redirect('accounts:login')

planilha/accounts/templates/accounts/change-password.html
{% extends 'base.html' %}

{% block title %}Alterar Senha{% endblock title %}

{% block content %}
	<div class="col-md-4 offset-md-4 mt-5">
		<div class="card">
				<form action="{% url 'accounts:change-password' %}" method="POST" class="mb-0">
					{% csrf_token %}
					<div class="card-header">
						<h5 class="card-title text-uppercase text-center">Alterar senha<i class="fas fa-key ml-2"></i></h5>
					</div>
					<div class="card-body">
						<div>
							{% include "components/field.html" with field=form.old_password %}

							{% include "components/field.html" with field=form.new_password1 %}

							{% include "components/field.html" with field=form.new_password2 %}
						</div>
						<button type="submit" class="btn btn-primary btn-block mb-2">Confirmar</button>
						<a href="{% url 'core:home' %}" class="text-decoration-none"><button type="button"
						class="btn btn-secondary btn-block">Cancelar</button></a>
					</div>
				</form>
		</div>
	</div>
{% endblock  %}

planilha/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock title %}

{% block content %}
  <div class="col-md-4 offset-md-4 mt-5">
    {% include 'components/messages.html' %}
    <div class="card">
      <div class="card-header">
        <h3 class="mt-1 mb-1 text-center">Login <i class="fad fa-sign-in"></i></h3>
      </div>
      <form method="POST" action="{% url 'accounts:login' %}">
        {% csrf_token %}
          <div class="card-body">
            {% include 'components/field.html' with field=form.username %}
            {% include 'components/field.html' with field=form.password %}
            <button type="submit" class="btn btn-info btn-block mt-2 mb-5">Entrar</button>
            <hr>
            <p class="text-center text-uppercase">Cadastre-se abaixo</p>
            <a href="{% url 'accounts:register' %}" class="btn btn-secondary btn-block mt-2">Cadastre-se</a>
            {% comment %} <a href="#" class="btn btn-success btn-block mt-5">Reuperar Senha</a> {% endcomment %}
          </div>
      </form>
    </div>
  </div>
{% endblock content %}

planilha/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}Cadastro{% endblock title %}

{% block content %}
      <div class="col-md-4 offset-md-4 mt-5">
        <div class="card">
          <div class="card-header">
            <h3 class="mt-1 mb-1 text-center">Cadastro <i class="far fa-cabinet-filing"></i></h3>
          </div>
          <form method="POST" action="{% url 'accounts:register' %}">
            {% csrf_token %}
              <div class="card-body">
              {% include 'components/field.html' with field=form.username %}
              {% comment %} <div id="error-spent"></div> {% endcomment %}
              {% include 'components/field.html' with field=form.email %}
              {% comment %} <div id="error-date"></div> {% endcomment %}
              {% include 'components/field.html' with field=form.password %}
              {% comment %} <div id="error-value"></div> {% endcomment %}
              {% include 'components/field.html' with field=form.password2 %}
              {% comment %} <div id="error-value"></div> {% endcomment %}
              <button type="submit" class="btn btn-info btn-block mt-2">Salvar</button>
              <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block mt-2">Voltar</a>
            </div>
          </form>
        </div>
      </div>
{% endblock content %}