planilha/accounts/urls.py
from django.urls import path

from planilha.accounts import views

app_name = 'accounts'


urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('sair/', views.logout_view, name='logout'),
    path(
        'mudar-senha/', views.CustomPasswordChangeView.as_view(), name='change-password'
    ),
]

planilha/core/urls.py
from django.urls import path

from planilha.core import views

app_name = 'core'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('deletar/<int:pk>/<str:month>', views.delete_spent_view, name='delete'),
    path(
        'alterar/<int:pk>/<str:month>/<int:year>',
        views.update_spent_view,
        name='update',
    ),
    path('adicionar/<str:month>/<int:year>', views.create_spent_view, name='create'),
    path('renda/<str:month>/<int:year>', views.income_view, name='income'),
    path('mes/<str:month>/', views.month_view, name='month'),
]

planilha/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('planilha.core.urls')),
    path('', include('planilha.accounts.urls')),
] + static(settings.MEDIA_URL, document=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

planilha/core/models.py
from datetime import date

from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
from django.db import models


class AbstractBaseModel(models.Model):
    created_at = models.DateTimeField(verbose_name='Criado', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Atualizado', auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return str(self.pk)


class Spent(AbstractBaseModel):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='spent')
    spent = models.CharField(verbose_name='Gasto', max_length=50, null=True, blank=True)
    month = models.IntegerField(verbose_name='Mês', default=date.today().month)
    year = models.IntegerField(verbose_name='Ano', default=date.today().year)
    value = models.DecimalField(
        'Valor', max_digits=15, decimal_places=2, null=True, blank=True
    )
    number_plots = models.IntegerField(verbose_name='Numero de parcelas', default=2)
    fixed_account = models.BooleanField(verbose_name='Conta fixa', default=False)
    parceled_out = models.BooleanField(verbose_name='Parcelada', default=False)

    class Meta:
        verbose_name = 'Gasto'
        verbose_name_plural = 'Gastos'
        ordering = ('-id',)

    def __str__(self):
        return self.spent


class Income(AbstractBaseModel):
    user = models.ForeignKey(
        'auth.User', on_delete=models.DO_NOTHING, related_name='income'
    )
    income = models.DecimalField(
        verbose_name='Renda Bruta Mensal',
        max_digits=15,
        decimal_places=2,
        default=0,
        validators=[MinValueValidator(0)],
    )
    month = models.IntegerField(verbose_name='Mês', default=date.today().month)
    year = models.IntegerField(verbose_name='Ano', default=date.today().year)
    save_percent = models.IntegerField(
        verbose_name='Pocentagem Ah Economizar',
        default=0,
        validators=[MaxValueValidator(100), MinValueValidator(0)],
    )

    class Meta:
        verbose_name = 'Renda Mensal Bruta'
        verbose_name_plural = 'Rendas Mensais Brutas'
        ordering = ('-id',)

    def __str__(self):
        return str(self.income)

planilha/core/forms.py
from django import forms

from planilha.core import models


class SpentForm(forms.ModelForm):
    spent = forms.CharField(label='Conta')
    value = forms.DecimalField(label='Valor', min_value=1.0)

    class Meta:
        model = models.Spent
        fields = [
            'spent',
            'value',
            'month',
            'year',
            'fixed_account',
            'parceled_out',
            'number_plots',
        ]

    def __init__(self, *args, **kwargs):
        self.month = kwargs.pop('month', None)
        self.year = kwargs.pop('year', None)
        super(SpentForm, self).__init__(*args, **kwargs)

        self.fields['month'].required = False
        self.fields['year'].required = False

    def clean(self):
        new_spent = self.cleaned_data.get('spent')
        new_value = self.cleaned_data.get('value')
        new_number_plots = self.cleaned_data.get('number_plots')

        qs = models.Spent.objects.filter(
            spent=new_spent, value=new_value, number_plots=new_number_plots
        )
        if qs.exists():
            raise forms.ValidationError('Conta já existe')

    def save(self):
        self.instance.month = self.month
        self.instance.year = self.year
        self.instance.save()


class IncomeForm(forms.ModelForm):
    income = forms.CharField(
        label='Renda de ',
        widget=forms.TextInput(attrs={'type': 'tel'}),
    )
    save_percent = forms.CharField(
        label='Guardar em %',
        widget=forms.TextInput(attrs={'type': 'tel'}),
    )
    year = forms.CharField(
        label='Definir ano',
        required=False,
        widget=forms.TextInput(attrs={'type': 'tel'}),
    )

    class Meta:
        model = models.Income
        fields = ['income', 'save_percent', 'year']

planilha/core/views.py
from datetime import date

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy

from planilha.core.forms import SpentForm, IncomeForm
from planilha.core.models import Spent, Income
from planilha.core import months


@login_required
def home_view(request):
    context = {}
    context['form'] = SpentForm()
    context['form_income'] = IncomeForm()
    context['months'] = months.MONTHS

    context['spents'] = (
        Spent.objects.filter(user=request.user)
        .values('pk', 'spent', 'value', 'created_at', 'updated_at')
        .order_by('-updated_at')[:10]
    )

    return render(request, 'core/home.html', context)


@login_required
def income_view(request, month, year=date.today().year):
    month_number = months.MONTHS.get(month)
    income, _ = Income.objects.get_or_create(
        user=request.user, month=month_number, year=year
    )
    if request.method == 'POST':
        form = IncomeForm(data=request.POST, instance=income)

        if form.is_valid():
            form.save()

            messages.success(request, 'Dados SALVO com sucesso.')
            return JsonResponse(
                {'url': reverse_lazy('core:month', kwargs={'month': month})}, status=200
            )

        return JsonResponse({'errors': form.errors}, status=400)

    return JsonResponse({'income': income.income, 'save_percent': income.save_percent})


@login_required
def delete_spent_view(request, pk, month):
    Spent.objects.get(pk=pk).delete()

    messages.success(request, 'Conta DELETADA com sucesso.')
    return JsonResponse({'url': reverse_lazy('core:month', args=[month])}, status=200)


@login_required
def update_spent_view(request, pk, month, year):
    spent = Spent.objects.get(user=request.user, pk=pk)
    month_number = months.MONTHS.get(month)

    if request.method == 'POST':
        form = SpentForm(
            data=request.POST,
            instance=spent,
            month=month_number,
            year=year,
        )
        if form.is_valid():
            form.save()

            messages.success(
                request, f'Conta <strong>{form.instance}</strong> ALTERADA com sucesso.'
            )
            return JsonResponse(
                {'url': reverse_lazy('core:month', args=[month])}, status=200
            )

        return JsonResponse({'errors': form.errors}, status=400)

    return JsonResponse(
        {
            'spent': spent.spent,
            'value': spent.value,
            'fixed_account': spent.fixed_account,
        }
    )


@login_required
def create_spent_view(request, month, year):
    if request.method == 'POST':
        month_number = months.MONTHS.get(month)
        form = SpentForm(
            data=request.POST,
            instance=Spent(user=request.user),
            month=month_number,
            year=year,
        )
        if form.is_valid():
            form.save()

            messages.success(
                request,
                f'Conta <strong>{form.instance}</strong> ADICIONADA com sucesso.',
            )
            return JsonResponse(
                {'url': reverse_lazy('core:month', args=[month])}, status=200
            )

        return JsonResponse({'errors': form.errors}, status=400)


@login_required
def month_view(request, month):
    context = {}
    form_income = IncomeForm()
    month_number = months.MONTHS.get(month)
    month_name = ''.join([k for k, v in months.MONTHS.items() if v == month_number])
    year = int(request.GET.get('year')) if request.GET.get('year') else date.today().year

    context['form'] = SpentForm()
    context['month_name'] = month_name
    context['form_income'] = form_income
    context['year'] = year
    context['fixeds_accounts'] = Spent.objects.filter(
        user=request.user, fixed_account=True
    ).values('pk', 'spent', 'value')

    context['spents'] = (
        Spent.objects.filter(
            user=request.user, year=year, fixed_account=False, parceled_out=True
        )
    ).values('pk', 'spent', 'value', 'parceled_out', 'number_plots')

    income = (
        Income.objects.filter(user=request.user, month=month_number, year=year)
        .values('income', 'save_percent')
        .last()
    )

    if income:
        context['income'] = income
        context['percent'] = income['income'] * income['save_percent'] / 100
        if context['spents']:
            context['total_spents'] = (
                Spent.objects.filter(
                    user=request.user,
                    month=month_number,
                    year=year,
                )
                .aggregate(total=Sum('value'))
                .get('total')
            )
            context['balance'] = (
                income['income'] - context['total_spents'] - context['percent']
            )

    return render(request, 'core/month.html', context)

planilha/core/templates/core/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
  {% include 'components/messages.html' %}

  <div class="card mt-5">
  <div class="card-header bg-dark"></div>
    <div class="card-body text-center">
      <h3>Sistema De Gastos <i class="fad fa-money-check-edit-alt"></i></h3>
    </div>
  </div>
  <div class="card mt-5">
    <div class="card-header text-center"><h4>Meses</h4></div>
    <div class="card-body text-center">
      {% for month in months %}
        <a href="{% url 'core:month' month=month %}"><button class="btn btn-primary mt-2 ml-2">{{ month|slice:':3' }}</button></a>
      {% endfor %}
    </div>
  </div>
  <div class="card card-table mt-5 mb-3">
  <div class="card-header text-center text-uppercase"><h5>Últimas 10 contas - atualizadas</h5></div>
    <div class="card-body table-responsive p-0">
      <table class="table table-hover text-center">
        <thead>
          <tr>
            <th>Descrição</th>
            <th>Data da compra</th>
            <th>Valor</th>
            <th>Criada</th>
            <th>Atualizada</th>
          </tr>
        </thead>
        <tbody>
          {% for spent in spents %}
            <tr>
              <td id="spent-table">{{ spent.spent }}</td>
              <td id="date-table">{{ spent.date|date:"d/m/Y" }}</td>
              <td id="value-table">R$ {{ spent.value }}</td>
              <td id="value-table">{{ spent.created_at|date:"d/m/Y H:i:s" }}</td>
              <td id="value-table">{{ spent.updated_at|date:"d/m/Y H:i:s" }}</td>
            </tr>
          {% empty %}
            <td class="text-center text-danger text-uppercase" colspan="5">Não ah contas cadastradas</td>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content %}

planilha/core/templates/core/login.html
{% extends 'base.html' %}

{% block title %}<title>Login</title>{% endblock title %}

{% block content %}
  <div class="col-md-4 offset-md-4 mt-5">
    {% include 'components/messages.html' %}
    <div class="card">
      <div class="card-header">
        <h3 class="mt-1 mb-1 text-center">Login <i class="fad fa-sign-in"></i></h3>
      </div>
      <form method="POST" action="{% url 'core:login' %}">
        {% csrf_token %}
          <div class="card-body">
            {% include 'components/field.html' with field=form.username %}
            {% include 'components/field.html' with field=form.password %}
            <button type="submit" class="btn btn-info btn-block">Entrar</button>
          </div>
      </form>
    </div>
  </div>
{% endblock content %}

planilha/core/templates/core/modal-delete-spent.html
<div class="modal fade" id="delete-spent">
  <div class="modal-dialog" role="document">
      <form method="POST" class="modal-content" id="modal-delete">
      {% csrf_token %}
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Excluir Gasto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div class="form-group">
            <label for="">Tem certeza que deseja excluir esse gasto?</label>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary" id="btn-delete">Confirmar</button>
      </div>
    </form>
  </div>
</div>

planilha/core/templates/core/modal-spent.html
{% load widget_tweaks %}

<div class="modal fade" id="spent">
  <div class="modal-dialog" role="document">
      <form method="POST" class="modal-content" id="modal-spent">
      {% csrf_token %}
      <div class="modal-header">
        <h5 class="modal-title" id="modal-label"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="all-error-spent"></div>
        {% include 'components/field.html' with field=form.spent %}
        <div id="error-spent"></div>
        {% include 'components/field.html' with field=form.value %}
        <div id="error-value"></div>
        <div class="form-check fixed_account">
          {{ form.fixed_account|add_class:"form-check-input" }}
          <label class="form-check-label" for="{{ form.fixed_account.id_for_label }}">{{ form.fixed_account.label }}</label>
        </div>
        <div class="form-check mb-2 parceled_out">
          {{ form.parceled_out|add_class:"form-check-input" }}
          <label class="form-check-label" for="{{ form.parceled_out.id_for_label }}">{{ form.parceled_out.label }}</label>
        </div>
        <div class="number_plots">
          {% include 'components/field.html' with field=form.number_plots %}
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn btn-primary" id="btn-create">Salvar</button>
      </div>
    </form>
  </div>
</div>

planilha/core/templates/core/month.html
{% extends 'base.html' %}
{% load month_tags %}

{% block title %}Contas de {{ month_name }}{% endblock title %}

{% block content %}
  {% include 'components/messages.html' %}

  <div class="mt-5">
    <div class="form-row">
      <div class="col-md-4">
        <form action="{% url 'core:month' month=month_name %}" method="GET">
          {% include 'components/field.html' with field=form_income.year placeholder=year %}
          <button class="btn btn-success btn-sm">Definir</button>
          <a href="{% url 'core:home' %}"><button type="button" class="btn btn-secondary btn-sm">voltar</button></a>
        </form>
      </div>
      <div class="col-md-4">
        <form action="{% url 'core:income' month=month_name year=year %}" method="POST">
          {% csrf_token %}
          {% include 'components/field.html' with field=form_income.income month=month_name %}
          <div id="error-income"></div>
          <button id="btn-income" class="btn btn-primary btn-sm">Salvar</button>
      </div>
      <div class="col-md-4">
          {% include 'components/field.html' with field=form_income.save_percent %}
          <div id="error-save-percent"></div>
        </form>
      </div>
    <div class="card card-infos p-0 w-100">
      <div class="card-header text-center font-weight-bold">Informações de {{ month_name }} de {{ year }}</div>
      <div class="mt-2 text-center infos p-0">
        <p>Saldo final = R$ <strong>{% if income.income %}{{ balance|default:income.income }}{% else %}0,00{% endif %}</strong></p>
        <p class="text-success">Poupança = R$ {{ percent|default:"0,00" }}</p>
        <p class="text-danger">Total das contas = R$ <strong>{{ total_spents|default:"0,00" }}</strong></p>
      </div>
    </div>
  </div>
  </div>
  <div class="card card-table mt-5 mb-3">
  <div class="card-header text-center text-uppercase"><h5>Contas Fixas</h5>
  </div>
    <div class="card-body table-responsive p-0">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Descrição</th>
            <th>Data da compra</th>
            <th>Valor</th>
          </tr>
        </thead>
        <tbody>
          {% for fixed_account in fixeds_accounts %}
            <tr>
              <td>{{ fixed_account.spent }}</td>
              <td>{{ fixed_account.date|date:"d/m/Y" }}</td>
              <td>R$ {{ fixed_account.value }}</td>
              <td class="text-right">
                <a class="btn btn-warning btn-sm p-1 update" data-toggle="modal"
                data-target="#spent" data-url={% url 'core:update' pk=fixed_account.pk month=month_name year=year %}><i class="fad fa-pencil-alt"></i> Alterar</a>

                <a class="btn btn-danger btn-sm p-1 text-white delete" data-toggle="modal"
                data-target="#delete-spent" data-url={% url 'core:delete' pk=fixed_account.pk month=month_name %}><i class="fas fa-trash-alt"></i> Excluir</a>
              </td>
            </tr>
          {% empty %}
            <td class="text-center text-danger text-uppercase" colspan="4">Não Ah Contas Cadastradas</td>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="card card-table mt-5 mb-3">
  <div class="card-header text-center text-uppercase"><h5>Contas de {{ month_name }} de {{ year }}</h5>
  <a class="btn btn-info btn-sm create" data-toggle="modal" data-target="#spent"
  data-url={% url 'core:create' month=month_name year=year %}><i class="fas fa-plus-square"></i> Adicionar</a>
  </div>
    <div class="card-body table-responsive p-0">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Descrição</th>
            <th>Valor</th>
            <th>Parcelada</th>
            <th>Vezes</th>
          </tr>
        </thead>
        <tbody>
          {% for spent in spents %}
            <tr>
              <td>{{ spent.spent }}</td>
              <td>R$ {{ spent.value }}</td>
              <td>{{ spent.parceled_out|true_or_false|safe }}</td>
              {% if spent.parceled_out %}
               <td>{{ spent.number_plots }}</td>
              {% else %}
                <td></td>
              {% endif %}
              <td></td>
              <td class="text-right">
                <a class="btn btn-warning btn-sm p-1 update" data-toggle="modal"
                data-target="#spent" data-url={% url 'core:update' pk=spent.pk month=month_name year=year %}><i class="fad fa-pencil-alt"></i> Alterar</a>

                <a class="btn btn-danger btn-sm p-1 text-white delete" data-toggle="modal"
                data-target="#delete-spent" data-url={% url 'core:delete' pk=spent.pk month=month_name %}><i class="fas fa-trash-alt"></i> Excluir</a>
              </td>
            </tr>
          {% empty %}
            <td class="text-center text-danger text-uppercase" colspan="4">Não Ah Contas Cadastradas</td>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% include 'core/modal-delete-spent.html' %}
{% include 'core/modal-spent.html' with form=form %}
{% endblock content %}

{% block js %}
  <script>
    $(function() {
        $('.delete').on('click', function() {
        let url = $(this).attr("data-url");
        $('#modal-delete').prop('action', url);
      });
      $('.update').on('click', function() {
        let url = $(this).attr("data-url");
        $('#modal-spent').prop('action', url);
        $('#modal-label').html('Alterar Conta de {{ month_name }}')

        $.get(url, function(data) {
          $('#id_spent').val(data.spent)
          $('#id_value').val(data.value)
          if (data.fixed_account) {
            $('#id_fixed_account').prop('checked', true)
            $('#modal-label').html('Alterar Conta fixa')
          }
        });
      });

      $('.number_plots').prop('hidden', true)
      $('#id_parceled_out').click(function() {
        if ($(this).is(':checked')) {
          $('.number_plots').prop('hidden', false)
          $('.fixed_account').prop('hidden', true)
        } else {
          $('.number_plots').prop('hidden', true)
          $('.fixed_account').prop('hidden', false)
        }
      });

      $('#id_fixed_account').click(function() {
        if ($(this).is(':checked')) {
          $('.parceled_out').prop('hidden', true)
        } else {
          $('.parceled_out').prop('hidden', false)
        }
      });

      $('.create').on('click', function() {
        let modal_spent = $('#modal-spent')
        let url = $(this).attr("data-url");
        modal_spent.prop('action', url);
        modal_spent.find('input[name="spent"], input[name="date"], input[name="value"]').val('')
        $('#modal-label').html('Adicionar Conta de {{ month_name }}')
      });

      $.get('/renda/{{ month_name }}/{{ year }}', function(data) {
          $('#id_income').val(data.income)
          $('#id_save_percent').val(data.save_percent)
        });

      function spentForm(url, form) {
        $.ajax({
          url: url,
          method: 'POST',
          headers: {'X-CSRFToken': '{{ csrf_token }}'},
          data: form.serialize(),
          dataType: 'json',
          success: function() {
            location.reload();
          },
          error: function(data) {
            errors = data.responseJSON.errors

            if (errors.spent) {
              $('input[name="spent"]').addClass('is-invalid');
              $('#error-spent').addClass('has-error text-danger').html(errors.spent);
            }
            if (errors.date) {
              $('input[name="date"]').addClass('is-invalid');
              $('#error-date').addClass('has-error text-danger').html(errors.date);
            }
            if (errors.value) {
              $('input[name="value"]').addClass('is-invalid');
              $('#error-value').addClass('has-error text-danger').html(errors.value);
            } else {
              $('#error-value').addClass('has-error text-danger').html(errors.__all__);
            }
          }
        });
      }

      function incomeForm(url, form) {
        $.ajax({
          url: url,
          method: 'POST',
          headers: {'X-CSRFToken': '{{ csrf_token }}'},
          data: form.serialize(),
          dataType: 'json',
          success: function() {
            location.reload();
          },
          error: function(data) {
            errors = data.responseJSON.errors
            if (errors.income) {
              $('input[name="income"]').addClass('is-invalid');
              $('#error-income').addClass('has-error text-danger').html(errors.income);
            }
            if (errors.save_percent) {
              $('input[name="save_percent"]').addClass('is-invalid');
              $('#error-save-percent').addClass('has-error text-danger').html(errors.save_percent);
            }
          }
        });
      }
      function deleteForm(url, form) {
        $.ajax({
          url: url,
          method: 'POST',
          headers: {'X-CSRFToken': '{{ csrf_token }}'},
          data: form.serialize(),
          dataType: 'json',
          success: function() {
            location.reload();
          },
        });
      }

      $('#btn-income').on('click', function(event) {
        event.preventDefault();
        form = $(this).closest('form');
        url = $(this).closest('form').attr('action');
        incomeForm(url, form);
      });

      $('#btn-create').on('click', function(event) {
        event.preventDefault();
        form = $(this).closest('form');
        url = $(this).closest('form').attr('action');
        spentForm(url, form)
      });
      $('#btn-delete').on('click', function(event) {
        event.preventDefault();
        form = $(this).closest('form');
        url = $(this).closest('form').attr('action');
        deleteForm(url, form)
      });
    });
  </script>
{% endblock js %}