planilha/accounts/urls.py
from django.urls import path

from planilha.accounts import views

app_name = 'accounts'


urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('sair/', views.logout_view, name='logout'),
    path(
        'mudar-senha/', views.CustomPasswordChangeView.as_view(), name='change-password'
    ),
]

planilha/core/urls.py
from django.urls import path

from planilha.core import views

app_name = 'core'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('deletar/<int:pk>/<str:month>', views.delete_spent_view, name='delete'),
    path(
        'alterar/<int:pk>/<str:month>/<int:year>',
        views.update_spent_view,
        name='update',
    ),
    path('adicionar/<str:month>/<int:year>', views.create_spent_view, name='create'),
    path('renda/<str:month>/<int:year>', views.income_view, name='income'),
    path('mes/<str:month>/', views.month_view, name='month'),
]

planilha/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('planilha.core.urls')),
    path('', include('planilha.accounts.urls')),
] + static(settings.MEDIA_URL, document=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

planilha/core/models.py
from datetime import date

from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
from django.db import models


class AbstractBaseModel(models.Model):
    created_at = models.DateTimeField(verbose_name='Criado', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Atualizado', auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return str(self.pk)


class Spent(AbstractBaseModel):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='spent')
    spent = models.CharField(verbose_name='Gasto', max_length=50, null=True, blank=True)
    month = models.IntegerField(verbose_name='Mês', default=date.today().month)
    year = models.IntegerField(verbose_name='Ano', default=date.today().year)
    value = models.DecimalField(
        'Valor', max_digits=15, decimal_places=2, null=True, blank=True
    )
    number_plots = models.IntegerField(verbose_name='Numero de parcelas', default=2)
    fixed_account = models.BooleanField(verbose_name='Conta fixa', default=False)
    parceled_out = models.BooleanField(verbose_name='Parcelada', default=False)

    class Meta:
        verbose_name = 'Gasto'
        verbose_name_plural = 'Gastos'
        ordering = ('-id',)

    def __str__(self):
        return self.spent


class Income(AbstractBaseModel):
    user = models.ForeignKey(
        'auth.User', on_delete=models.DO_NOTHING, related_name='income'
    )
    income = models.DecimalField(
        verbose_name='Renda Bruta Mensal',
        max_digits=15,
        decimal_places=2,
        default=0,
        validators=[MinValueValidator(0)],
    )
    month = models.IntegerField(verbose_name='Mês', default=date.today().month)
    year = models.IntegerField(verbose_name='Ano', default=date.today().year)
    save_percent = models.IntegerField(
        verbose_name='Pocentagem Ah Economizar',
        default=0,
        validators=[MaxValueValidator(100), MinValueValidator(0)],
    )

    class Meta:
        verbose_name = 'Renda Mensal Bruta'
        verbose_name_plural = 'Rendas Mensais Brutas'
        ordering = ('-id',)

    def __str__(self):
        return str(self.income)

planilha/core/forms.py
from django import forms

from planilha.core import models


class SpentForm(forms.ModelForm):
    spent = forms.CharField(label='Conta')
    value = forms.DecimalField(label='Valor', min_value=1.0)

    class Meta:
        model = models.Spent
        fields = [
            'spent',
            'value',
            'month',
            'year',
            'fixed_account',
            'parceled_out',
            'number_plots',
        ]

    def __init__(self, *args, **kwargs):
        self.month = kwargs.pop('month', None)
        self.year = kwargs.pop('year', None)
        super(SpentForm, self).__init__(*args, **kwargs)

        self.fields['month'].required = False
        self.fields['year'].required = False

    def clean(self):
        new_spent = self.cleaned_data.get('spent')
        new_value = self.cleaned_data.get('value')
        new_number_plots = self.cleaned_data.get('number_plots')

        qs = models.Spent.objects.filter(
            spent=new_spent, value=new_value, number_plots=new_number_plots
        )
        if qs.exists():
            raise forms.ValidationError('Conta já existe')

    def save(self):
        self.instance.month = self.month
        self.instance.year = self.year
        self.instance.save()


class IncomeForm(forms.ModelForm):
    income = forms.CharField(
        label='Renda de ',
        widget=forms.TextInput(attrs={'type': 'tel'}),
    )
    save_percent = forms.CharField(
        label='Guardar em %',
        widget=forms.TextInput(attrs={'type': 'tel'}),
    )
    year = forms.CharField(
        label='Definir ano',
        required=False,
        widget=forms.TextInput(attrs={'type': 'tel'}),
    )

    class Meta:
        model = models.Income
        fields = ['income', 'save_percent', 'year']

planilha/core/views.py
from datetime import date

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy

from planilha.core.forms import SpentForm, IncomeForm
from planilha.core.models import Spent, Income
from planilha.core import months


@login_required
def home_view(request):
    context = {}
    context['form'] = SpentForm()
    context['form_income'] = IncomeForm()
    context['months'] = months.MONTHS

    context['spents'] = (
        Spent.objects.filter(user=request.user)
        .values('pk', 'spent', 'value', 'created_at', 'updated_at')
        .order_by('-updated_at')[:10]
    )

    return render(request, 'core/home.html', context)


@login_required
def income_view(request, month, year=date.today().year):
    month_number = months.MONTHS.get(month)
    income, _ = Income.objects.get_or_create(
        user=request.user, month=month_number, year=year
    )
    if request.method == 'POST':
        form = IncomeForm(data=request.POST, instance=income)

        if form.is_valid():
            form.save()

            messages.success(request, 'Dados SALVO com sucesso.')
            return JsonResponse(
                {'url': reverse_lazy('core:month', kwargs={'month': month})}, status=200
            )

        return JsonResponse({'errors': form.errors}, status=400)

    return JsonResponse({'income': income.income, 'save_percent': income.save_percent})


@login_required
def delete_spent_view(request, pk, month):
    Spent.objects.get(pk=pk).delete()

    messages.success(request, 'Conta DELETADA com sucesso.')
    return JsonResponse({'url': reverse_lazy('core:month', args=[month])}, status=200)


@login_required
def update_spent_view(request, pk, month, year):
    spent = Spent.objects.get(user=request.user, pk=pk)
    month_number = months.MONTHS.get(month)

    if request.method == 'POST':
        form = SpentForm(
            data=request.POST,
            instance=spent,
            month=month_number,
            year=year,
        )
        if form.is_valid():
            form.save()

            messages.success(
                request, f'Conta <strong>{form.instance}</strong> ALTERADA com sucesso.'
            )
            return JsonResponse(
                {'url': reverse_lazy('core:month', args=[month])}, status=200
            )

        return JsonResponse({'errors': form.errors}, status=400)

    return JsonResponse(
        {
            'spent': spent.spent,
            'value': spent.value,
            'fixed_account': spent.fixed_account,
        }
    )


@login_required
def create_spent_view(request, month, year):
    if request.method == 'POST':
        month_number = months.MONTHS.get(month)
        form = SpentForm(
            data=request.POST,
            instance=Spent(user=request.user),
            month=month_number,
            year=year,
        )
        if form.is_valid():
            form.save()

            messages.success(
                request,
                f'Conta <strong>{form.instance}</strong> ADICIONADA com sucesso.',
            )
            return JsonResponse(
                {'url': reverse_lazy('core:month', args=[month])}, status=200
            )

        return JsonResponse({'errors': form.errors}, status=400)


@login_required
def month_view(request, month):
    context = {}
    form_income = IncomeForm()
    month_number = months.MONTHS.get(month)
    month_name = ''.join([k for k, v in months.MONTHS.items() if v == month_number])
    year = int(request.GET.get('year')) if request.GET.get('year') else date.today().year

    context['form'] = SpentForm()
    context['month_name'] = month_name
    context['form_income'] = form_income
    context['year'] = year
    context['fixeds_accounts'] = Spent.objects.filter(
        user=request.user, fixed_account=True
    ).values('pk', 'spent', 'value')

    context['spents'] = (
        Spent.objects.filter(
            user=request.user, year=year, fixed_account=False, parceled_out=True
        )
    ).values('pk', 'spent', 'value', 'parceled_out', 'number_plots')

    income = (
        Income.objects.filter(user=request.user, month=month_number, year=year)
        .values('income', 'save_percent')
        .last()
    )

    if income:
        context['income'] = income
        context['percent'] = income['income'] * income['save_percent'] / 100
        if context['spents']:
            context['total_spents'] = (
                Spent.objects.filter(
                    user=request.user,
                    month=month_number,
                    year=year,
                )
                .aggregate(total=Sum('value'))
                .get('total')
            )
            context['balance'] = (
                income['income'] - context['total_spents'] - context['percent']
            )

    return render(request, 'core/month.html', context)

planilha/core/templates/components/field-error.html
{% for error in field.errors %}
  <div class="invalid-feedback">{{ error }}</div>
{% endfor %}

planilha/core/templates/components/field.html
{% load widget_tweaks %}

<div class="form-group">
  {% with class=class|default:"" %}
		{% if not field.field.widget.input_type == 'hidden' and field.label %}
			<label for="{{ field.id_for_label }}" class="text-bold">
				{{ field.label }}{{ month }}{% if field.field.required %}*{% endif %}
			</label>
		{% endif %}

		{% if field.errors %}
			{% render_field field|add_class:class|add_class:'is-invalid' class="form-control" %}
		{% else %}
			{% render_field field|add_class:class class="form-control" placeholder=placeholder %}
			{% if field.help_text %}
				<p class="help-block"><small>{{ field.help_text }}</small></p>
			{% endif %}
		{% endif %}

		{% include "components/field-error.html" with field=field %}
  {% endwith%}
</div>

planilha/core/templates/components/footer.html
<footer class="page-footer font-small bg-dark">
  <div class="container pt-2">
    <div class="row">
      <div class="col text-center mb-3">
        <a class="text-white">Powered by - Herbety Paulo</a>
        <a href="https://github.com/Pbezerra-dev" class="ml-3 text-white"><i class="fab fa-github"></i></a>
        <a href="https://www.linkedin.com/in/herbety-paulo/" class="ml-3 text-white">
          <i class="fab fa-linkedin"></i></a>
      </div>
    </div>
  </div>
</footer>

planilha/core/templates/components/form-error.html
{% if form.non_field_errors %}
  <div class="card bg-danger mb-3">
    <div class="text-white bg-danger"></div>
    {% for error in form.non_field_errors %}
      <div class="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
        class="text-white" aria-hidden="true">&times;</span></button>
        <p class="mb-0 text-white">{{ error }}</p>
      </div>
    {% endfor %}
  </div>
{% endif %}

planilha/core/templates/components/messages.html
{% for message in messages %}
	<div class="alert {{ message.tags }} text-center mt-3" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
		{{ message|safe }}
	</div>
{% endfor %}

planilha/core/templates/components/navbar.html
<!--_nav.html-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
	<div class="container">
		{% if user.is_authenticated %}
		<div class="row">
			<div class="col">
				<a class="navbar-brand" href="{% url 'core:home' %}">Home
				<i class="fad fa-home text-white"></i></a>
			</div>
		</div>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
			aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse mr-3" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle font-weight-bold" href="#" id="navbarDropdown"
						role="button" data-toggle="dropdown"
						aria-haspopup="true" aria-expanded="false">Usuário: {{ user }}</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'accounts:change-password' %}">Alterar senha</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{% url 'accounts:logout' %}">Sair</a>
					</div>
				</li>
			</ul>
		</div>
		{% else %}
			<h3 class="text-white mx-auto">
			Planilha De Gastos <i class="fad fa-money-check-edit-alt"></i></h3>
		{% endif %}
	</div>
</nav>